### ISSUE TITLE
Tilde ~ character in URLs breaks HTML links

### ISSUE THREAD

**Issue by bengarrett** [fabiospampinato/notable#308] opened 2019-01-21 02:26 UTC
- **Fedora Linux**:
- **29**:

### Current behavior

In a note, add a URL which includes a **~**

`http://example.com/~example/`

### Expected behavior

It should return a link with the URL but instead returns a broken link.

```
http://example.com/~{/left/lbrace{e}/right/rbrace}{/left/lbrace{x}/right/rbrace}{/left/lbrace{a}/right/rbrace}{/left/lbrace{m}/right/rbrace}{/left/lbrace{p}/right/rbrace}{/frac{{/le}}{{
```

**Comment by bendem** [comment] 2019-01-21 07:53
Duplicate of #235. This is because the url contains a tilde that's interpreted by katex

**Closed** 2019-01-21 13:20 UTC
