### ISSUE TITLE
App crash on Searching (Ubuntu 17.10)

### ISSUE THREAD

**Issue by zziz** [fabiospampinato/notable#86] opened 2018-12-28 15:36 UTC
I get following crash message when I search on Notable. 

Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Error (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:13:314)
    at ca (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:14:166)
    at t (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:118:40)
    at af (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:150:11)
    at fg (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:154:21)
    at Q (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:168:468)
    at Ag (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:204:16)
    at lh (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:205:271)
    at mh (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:220:233)
    at Ph (file:///opt/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:219:143)

**Comment by fabiospampinato** [comment] 2018-12-28 15:55
Duplicate of #2.

**Closed by fabiospampinato** 2018-12-28 15:55 UTC
