### ISSUE TITLE
Icon default in .deb package

### ISSUE THREAD

**Issue by lucasgray** [fabiospampinato/notable#90] opened 2018-12-28 17:50 UTC
Ubuntu 18.04.01 LTS

Installed via .deb, everything works perfectly but the icon did not show up - I modified `/usr/share/applications/notable.desktop`, specifically the line 

```
Icon=/opt/Notable/resources/src/renderer/template/dist/images/icon.png
```

To add an icon from the installed resources.  Previously the value `notable` only showed a default Ubuntu gears icon.

**Comment by fabiospampinato** [comment] 2018-12-28 17:52
I've noticed that as well, we are bundling the app with [electron-builder](https://github.com/electron-userland/electron-builder), if anybody has any clue on how to configure it properly for this let me know.

**Comment by superhawk610** [comment] 2018-12-31 20:33
Haven't had time to fork and test this out, but seems like `icon.png` may be the issue - [see this thread](https://github.com/electron-userland/electron-builder/issues/2577#issuecomment-384690260).

**Comment by fabiospampinato** [comment] 2019-01-03 17:11
@superhawk610 thanks for the info, it seems the way to fix this is a bit laborious. If anyone would like to simply use the `.ico` version of the icon rather than the `.png` one for Linux builds and check if it works it would help me fix this faster.

**Comment by mikaelmello** [comment] 2019-01-04 15:47
+1.

Only that this time, on 1.1.0, `/opt/Notable/resources/src/renderer/template/dist/images/icon.png` does not exist. I had to download the icon and manually point it in the `.desktop` file

**Comment by fabiospampinato** [comment] 2019-01-04 15:53
The compiled "template" isn't bundled with the app, you have to generate it yourself (`npm run svelto:dev`).

**Comment by mikaelmello** [comment] 2019-01-04 16:08
Thanks for the info.

Anyway, I can't seem to get _any_ icon to work with Notable. I've tried multiple three absolute paths and even went as far as setting `Icon=code` or `Icon=google-chrome` to see if anything worked.

Do you have any idea why?


By the way, great project once again, I've set it up on Windows (allowing edits on mobile via google-drive) and now I'm trying to make it work on Linux

**Comment by fabiospampinato** [comment] 2019-01-04 16:21
> Do you have any idea why?

@mikaelmello not really, but @superhawk610 linked to [this](https://github.com/electron-userland/electron-builder/issues/2577#issuecomment-384690260) post which makes me think that maybe  the `.ico` icon doesn't contain all the necessary sizes.

**Comment by tiotrom** [comment] 2019-01-23 02:11
Any progress on this? :) - No icon in Manjaro either and I kinda love the app thank you very much for making it!

**Comment by fabiospampinato** [comment] 2019-01-23 02:17
@tiotrom maybe it got fixed by https://github.com/fabiospampinato/notable/pull/258, which will be included in the next release.

**Comment by fabiospampinato** [comment] 2019-01-24 15:54
Just tested this under Lubuntu and the problem is fixed for me, feel free to reopen the issue if the next release won't fix this for you

**Closed by fabiospampinato** 2019-01-24 15:54 UTC
Labels: bug, help wanted
