### ISSUE TITLE
Check task's checkbox from view mode

### ISSUE THREAD

**Issue by ymjonline** [fabiospampinato/notable#257] opened 2019-01-10 17:56 UTC
- **OS Version**: Windows 10
- **Notable Version**: 1.1.0

### Current behavior

Not possible to toggle status of checkbox directly (à la Joplin, Typora etc)

![noteable_checkbox](https://user-images.githubusercontent.com/46528969/50986992-9a0d5f00-1508-11e9-87a2-85882b1b54e3.gif)

### Expected behavior

This would be extremely useful for task management. Quick change on status without having to play around with code.

I think Tasks/ToDo should be treated differently as changes for other component as by nature the workflow is not about _editing_ but rather about _toggling_ some productivity items. (the same way, you apply tags and status, without going in the header's code itself)

On the side note, dedicated ToDo "notes" (_à la_ Joplin) that could be 'checked' would be great.
So more data could be added to the task itself (description and maybe some time-related attributes e.g. due date)

**Comment by fabiospampinato** [comment] 2019-01-10 17:57
Duplicate of #169

**Closed by fabiospampinato** 2019-01-10 17:57 UTC
