### ISSUE TITLE
KaTeX is trying to render non-KaTeX expressions

### ISSUE THREAD

**Issue by fanghuaqi** [fabiospampinato/notable#235] opened 2019-01-08 06:15 UTC
The editor don't support markdown format like this
~~~
` --images ~/a/val --labels ~/aval.txt --label_offset 1 --aaa 0.875 --aaa RGB --aaa 0.aa --aa testlongline this is a longline`
~~~

![image](https://user-images.githubusercontent.com/1538922/50813189-8fa86500-1350-11e9-81cc-2c27fdb36d99.png)

![image](https://user-images.githubusercontent.com/1538922/50813195-9636dc80-1350-11e9-9e32-9d5f5d15e190.png)

**Comment by fabiospampinato** [comment] 2019-01-08 13:34
This is an issue with KaTeX, the text between tildes is kind of getting recognized as a math expression I think.

**Comment by fabiospampinato** [comment] 2019-01-24 01:41
Duplicate of #199

**Closed by fabiospampinato** 2019-01-24 01:41 UTC
Labels: bug
