### ISSUE TITLE
Support relative link

### ISSUE THREAD

**Issue by fireb1001** [fabiospampinato/notable#209] opened 2019-01-05 13:52 UTC
When i use relative link:
`
[a relative link](other_file.md)
`
it shows as it is, without any linkable text

**Comment by fabiospampinato** [comment] 2019-01-05 13:56
@fireb1001 thanks for the suggestion, this syntax should be supported too.

**Comment by RomanKornev** [comment] 2019-01-05 18:33
Related #205

**Comment by fabiospampinato** [comment] 2019-01-16 22:09
I'm closing this as a duplicate of #205.

The suggested way of writing a relative link:

```
[a relative link](other_file.md)
```

We can't actually support, as for instance `other_file.md` should be a perfectly [valid](https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it) domain in the Republic of Moldova and there's no way for us to distinguish between the two.

It should have instead be written as 

```
[a relative link](./other_file.md)
```

This we can support.

**Closed by fabiospampinato** 2019-01-16 22:09 UTC
Labels: enhancement

**Comment by stevemoser** [comment] 2019-11-01 13:56
I don't understand this limitation. Github supports the `[a relative link](other_file.md)` syntax in README files and the like.
