### ISSUE TITLE
Attachment and tags menus are blurry

### ISSUE THREAD

**Issue by matejdro** [fabiospampinato/notable#33] opened 2018-12-27 14:19 UTC
Attachment menu appears blurry for me:

![image](https://user-images.githubusercontent.com/507922/50483127-9945da80-09ea-11e9-9885-de3d18752568.png)

Interesting thing is that switching to Focused mode fixes the issue, but if I disable focused mode and reopen attachment menu, blurriness is back. 

I do not have display scaling enabled (scaling is set to 100%).

**Comment by RomanKornev** [comment] 2018-12-27 16:04
Can confirm the issue on Windows 10 1803 x64.
Edit Attachments and Edit Tags are affected.
But after switching to focus mode and back, Attachments are not blurry while Tags still are.
Also resizing sidebar can make Attachments blurry again.

**Comment by fabiospampinato** [comment] 2018-12-27 18:07
That's pretty weird. I've no idea why this is happening, sounds like an issue with Electron itself.

**Comment by fabiospampinato** [comment] 2018-12-28 02:34
@axtgr thanks for looking into this! It's weird that that property causes this, it really sounds like a chromium/electron bug 🤔 I guess I'll remove that property if that solved the problem.

**Comment by eitch** [comment] 2018-12-28 08:45
I can confirm this on Ubuntu Linux 18.10 as well.

**Comment by bendem** [comment] 2019-01-03 07:41
This also affects macos

**Comment by fabiospampinato** [comment] 2019-01-03 15:57
I can't reproduce this, not under macOS nor under a Windows VM.

@bendem do you perhaps change some display/scaling/resolution-related settings?

@axtgr I don't think having `will-change: transform` in `.middlebar > .layout-content` should impact the popovers, and they don't have the `will-change: transform` property.

In order to fix I need to reproduce the problem, if you guys can help me reproduce this, or if you can fix this yourself by forking the master branch, that'd be great.

**Comment by iwoloschin** [comment] 2019-01-03 18:59
On macOS I just noticed that tags are fine when displayed on my rMBP's internal screen, but are blurry when displayed on an external screen.  Turning on Focus Mode makes the tags not blurry on an external screen.

**Comment by RomanKornev** [comment] 2019-01-03 19:01
Can confirm: disabling `will-change: transform` in **`#middlebar > .layout-content`** fixes everything.
Attachments/tags are no longer blurry, middlebar and sidebar items are also less blurry.
Before: ![before](https://user-images.githubusercontent.com/5807561/50654823-2070f080-0f9f-11e9-8eb2-414e16e831b7.png)
After: ![after](https://user-images.githubusercontent.com/5807561/50654836-2ebf0c80-0f9f-11e9-8a04-8bd46ba17ac0.png)

**Comment by axtgr** [comment] 2019-01-03 19:12
@fabiospampinato I agree that this is a strange behavior, but the links in my first comment explain why this happens. By default, when Chromium animates an element, it rasterizes it on every frame. However, when `will-change: transform` is used, the element is only rasterized once the property is set. It improves the performance of the animation, but leads to rendering glitches like this one. 

The weirdest part in this case is that `will-change: transform` isn't even set on the element being animated or its parent, but on a completely unrelated one.

**Comment by fabiospampinato** [comment] 2019-01-04 02:18
Fixed by @RomanKornev, thank you! I'll include his commit in the next release.

**Closed** 2019-01-04 03:43 UTC
Labels: bug, help wanted
