### ISSUE TITLE
Drag and drop not working

### ISSUE THREAD

**Issue by ArneBachmann** [fabiospampinato/notable#177] opened 2019-01-03 06:34 UTC
I dropped a `*.txt` file onto the Notable GUI, the `+` appeared, but after drop nothing happened.
I would expect it to be imported and shown, or ask to copy into the notes, and show it.

**Comment by fabiospampinato** [comment] 2019-01-03 12:36
Duplicate of #15.

**Closed by fabiospampinato** 2019-01-03 12:37 UTC
