### ISSUE TITLE
Snap install failed 

### ISSUE THREAD

**Issue by lucasgray** [fabiospampinato/notable#91] opened 2018-12-28 17:52 UTC
Ubuntu 18.04.1 LTS

Received vague error trying to open Snap package.  Deb packed worked fine

![notable-snap-error](https://user-images.githubusercontent.com/293351/50523670-1169da00-0a97-11e9-9b09-bc6165794d48.png)

**Comment by fabiospampinato** [comment] 2018-12-28 17:54
Can you install other `.snap` apps successfully?

**Comment by lucasgray** [comment] 2018-12-28 17:55
Indeed, I've installed for example Intellij this way.  I'm not sure if there are logs to pull, I'll poke around and see if I can gather more info

**Comment by lucasgray** [comment] 2018-12-28 18:00
Found an error in syslog,

```Dec 28 11:56:26 lucas-AX370-Gaming-K5 gnome-software[3035]: failed to convert file to GsApp: no application was created for running file-to-app with refine-flags=require-license,require-url,require-size,require-version,require-history,require-setup-action,require-origin,require-related,require-menu-path,require-provenance,require-icon,require-permissions,require-origin-hostname,require-runtime,require-screenshots with failure-flags=use-events with timeout=60 with file=/home/lucas/Downloads/notable_1.0.1_amd64.snap on plugin=fwupd```

**Comment by fabiospampinato** [comment] 2018-12-28 18:10
@lucasgray I'm not sure what that's about 🤔

**Comment by ExpLog** [comment] 2018-12-30 12:58
I had the same problem. I believe the issue is that the snap isn't registered with the snap store, so it doesn't trust it. Try installing with `sudo snap --dangerous <path to notable snap>`.

**Comment by fabiospampinato** [comment] 2019-01-03 17:11
Publishing the app to the snap store is tracked here #98

**Comment by Lin-Buo-Ren** [comment] 2019-01-19 01:12
I believe this is simply currently not implemented in GNOME Software, maybe someone want to check out their issue tracker?

**Comment by fabiospampinato** [comment] 2019-01-19 23:19
It seems this is happening because the snap isn't published to the store, so I'm closing this as duplicate of #98

**Closed by fabiospampinato** 2019-01-19 23:19 UTC
Labels: bug
