### ISSUE TITLE
Some keyboard shortcuts stop working after window loses focus

### ISSUE THREAD

**Issue by RomanKornev** [fabiospampinato/notable#234] opened 2019-01-07 23:36 UTC
## Steps to reproduce:

1. Run Notable
1. Press Ctrl+E to edit note - works
1. Alt+tab to other window and make it in focus
1. Alt+tab back to Notable
1. Click anywhere in the window to bring it into focus
1. Ctrl+E **doesn't** work
1. Ctrl+Shift+E still works every time
1. Now Ctrl+E works again

---
Ctrl+Shift+E is handled by:https://github.com/fabiospampinato/notable/blob/1ec7a9975e22a2b42bbcc5cb5df62fc4b6d06e48/src/renderer/components/main/extra/shortcuts.tsx#L14-L17
While Ctrl+E:
https://github.com/fabiospampinato/notable/blob/1ec7a9975e22a2b42bbcc5cb5df62fc4b6d06e48/src/main/windows/main.ts#L122-L125
Setting `enabled: true` makes Ctrl+E work every time.
So something happenes to `flags` after window loses focus.
Other shortcuts in last linked file are also affected.

**Comment by fabiospampinato** [comment] 2019-01-08 00:44
@RomanKornev I can't reproduce with the provided steps 🤔 if you could debug what happens to the flags it would be great.

**Comment by RomanKornev** [comment] 2019-01-08 01:31
Maybe here?
https://github.com/fabiospampinato/notable/blob/1ec7a9975e22a2b42bbcc5cb5df62fc4b6d06e48/src/main/windows/main.ts#L29
I'm not very familiar with JS.

**Comment by fabiospampinato** [comment] 2019-01-08 01:34
@RomanKornev `flag` should be `false` upon first instantiation only 🤔I'll have to take closer look at this.

**Comment by RomanKornev** [comment] 2019-01-08 01:50
When focus is restored `initMenu` gets called with `flags` :`undefined`
https://github.com/fabiospampinato/notable/blob/1ec7a9975e22a2b42bbcc5cb5df62fc4b6d06e48/src/main/windows/window.ts#L121

**Comment by fabiospampinato** [comment] 2019-01-08 01:54
@RomanKornev good catch! We should probably store the previous flags object or something. I'm moving this to the "Next" milestone.

**Closed** 2019-01-16 21:57 UTC
Labels: bug

**Comment by RomanKornev** [comment] 2019-01-16 22:45
Can confirm the fix. Now shortcuts are working.
