### ISSUE TITLE
Sorting notes using drag&drop within a notebook

### ISSUE THREAD

**Issue by fbnlsr** [fabiospampinato/notable#193] opened 2019-01-04 15:49 UTC
I think it could be nice to be able to sort  notes using drag&drop within a notebook. I personally write classes using `.md` files, and having the possibility to order my notes using the mouse instead of having to rename each and every file would be absolutely amazing.

Notable to make use of the frontmatter for this, storing the order position in a variable that corresponds to a notebook name. Of course, ordering by date/filename/last updated should still be available.

**Comment by fabiospampinato** [comment] 2019-01-04 15:53
Duplicate of #69

**Closed by fabiospampinato** 2019-01-04 15:53 UTC
