### ISSUE TITLE
Bug when using split view mode

### ISSUE THREAD

**Issue by glowacky** [fabiospampinato/notable#355] opened 2019-01-25 21:36 UTC
- **OS Version**: MacOS 10.14.2
- **Notable Version**: 1.2.0

### Current behavior

Opened a (relatively large - 120 KB) note in split view mode, made some edits, and then tried to exit split view. There was a bit of a hiccup in the app, and suddenly 70% of the text in the note disappeared. A new Markdown file was saved to my computer as "*original note name* (2).md", and the original note was moved to the trash of my cloud storage service. In the app, the new note appeared in the list with a different style:

![image](https://user-images.githubusercontent.com/46864481/51774128-4e49e080-20d8-11e9-92eb-ce37c10e023c.png)

Luckily I was able to recover the original!

### Expected behavior

Note content should not be affected when exiting split view mode.

**Comment by fabiospampinato** [comment] 2019-01-25 21:46
There's currently a performance issue with large notes, I think this will probably be fixed once we switch to Monaco #203.

> and suddenly 70% of the text in the note disappeared. 

This is strange, is it possible that while the app froze maybe you executed some shortcuts that selected part of the note and then deleted it? 🤔 

> In the app, the new note appeared in the list with a different style:

Can you post the content of a note that reproduce this problem?

**Comment by amelandri** [comment] 2019-01-25 21:47
Something similar happened to me too. I can’t give you as many details as glowacky, but I ended up with a different style in note list: the reason was that the title meta data contained the ‘#’ character.

**Comment by fabiospampinato** [comment] 2019-01-26 16:42
I can reproduce when a note starts with `   # foo` for instance, the bug comes from whitespace getting removed only later on, fix coming soon.

**Closed** 2019-01-26 16:51 UTC
Labels: bug

**Comment by glowacky** [comment] 2019-01-26 19:35
Great, thanks!
