### ISSUE TITLE
Random snippets showing up in edit window from previous documents.

### ISSUE THREAD

**Issue by minusf** [fabiospampinato/notable#415] opened 2019-02-04 13:04 UTC
- **OS Version**: macOS mojave 10.14.3
- **Notable Version**: 1.3

### Current behavior

Jumping between documents shows pieces of other open documents in current document.
Screenshot:

<img width="757" alt="screenshot 2019-02-04 at 13 52 41" src="https://user-images.githubusercontent.com/3632883/52209805-5696de00-2885-11e9-9fb9-57ee298b2ab1.png">

That last line is non-editable snippet not present in the .md file.
This example is a bit misleading because the extra line is not from this file, but from a file that has exact same content.

### Expected behavior

Not show random snippets from other files.
This was present in 1.2 too btw.

**Comment by fabiospampinato** [comment] 2019-02-04 13:33
Duplicate of #160.

**Closed by fabiospampinato** 2019-02-04 13:33 UTC
