### ISSUE TITLE
Asterix causes bolding inside fix-width block

### ISSUE THREAD

**Issue by nikodemus** [fabiospampinato/notable#31] opened 2018-12-27 14:04 UTC
Example:

    a*b

renders as shown in the image. This should not occur, as seen eg. above.

![image](https://user-images.githubusercontent.com/153172/50482758-f47acb80-09f0-11e9-84aa-179f49e0d49e.png)

**Comment by fabiospampinato** [comment] 2018-12-27 18:04
Can you post a whole note that reproduces this? For me `a*b` get rendered correctly in preview mode, and the `*b` characters get rendered in italic in editing mode.

**Comment by fabiospampinato** [comment] 2019-01-24 00:39
Closing since I can't reproduce and no more info has been provided.

**Closed** 2019-01-24 00:39 UTC
Labels: needs more info

**Comment by nikodemus** [comment] 2019-06-03 07:22
Test

```
a*b
```

**Comment by nikodemus** [comment] 2019-06-03 07:22
Yeah, this is gone now. Thank you anonymous fixer of things!
