### ISSUE TITLE
Scrolling in edit mode cause some unexpected behavior in other notes

### ISSUE THREAD

**Issue by roccowang** [fabiospampinato/notable#252] opened 2019-01-10 06:35 UTC
- **OS Version**: macOS 10.14.2
- **Notable Version**: v1.1.0

### Current behavior

1. open a new note, write until the editor become scrollable, and **do some scroll**
2. keep in edit mode and open another note
3. see some unexpected, unselectable ending in editor...
4. go into preview mode then back to edit mode, and thing goes normal again.

### Expected behavior

not this weird

### Maybe noteworthy

1. nothing goes wrong if you dont scroll
2. things become normal after a preview/edit mode switch

### Screenshots

* normal note
    ![](https://ws2.sinaimg.cn/large/006tNc79gy1fz1h6qr974j31740m5776.jpg)
* scrolled long note
    ![](https://ws4.sinaimg.cn/large/006tNc79gy1fz1h8344q2j315w0kx3zf.jpg)
* go back to that normal note and do a cmd-a
    ![](https://ws4.sinaimg.cn/large/006tNc79gy1fz1h8v6nqgj31740m50vp.jpg)

**Comment by roccowang** [comment] 2019-01-11 07:07
ok :) really look forward to that!

**Comment by fabiospampinato** [comment] 2019-01-24 01:40
Duplicate of #160

**Closed by fabiospampinato** 2019-01-24 01:40 UTC
Labels: bug
