### ISSUE TITLE
Error running v1.0.1 release

### ISSUE THREAD

**Issue by ryan-mccaffrey** [fabiospampinato/notable#13] opened 2018-12-27 07:09 UTC
Just downloaded Notable on Mac with the Notable-1.0.1-mac.zip file. Upon starting the app and selecting the default location for storing notes, I get:

```
Error: Cannot get property 'webContents' on missing remote object 4
Error: Cannot get property 'webContents' on missing remote object 4
    at throwRPCError (/private/var/folders/tk/bp9b866n115c6s97xv5x518c0000gn/T/AppTranslocation/2495B446-26EC-4DE6-997A-820A11C22FD9/d/Notable.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/private/var/folders/tk/bp9b866n115c6s97xv5x518c0000gn/T/AppTranslocation/2495B446-26EC-4DE6-997A-820A11C22FD9/d/Notable.app/Contents/Resources/electron.asar/browser/rpc-server.js:397:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/private/var/folders/tk/bp9b866n115c6s97xv5x518c0000gn/T/AppTranslocation/2495B446-26EC-4DE6-997A-820A11C22FD9/d/Notable.app/Contents/Resources/electron.asar/browser/api/web-contents.js:293:13)
    at WebContents.emit (events.js:182:13)
    at metaToException (/private/var/folders/tk/bp9b866n115c6s97xv5x518c0000gn/T/AppTranslocation/2495B446-26EC-4DE6-997A-820A11C22FD9/d/Notable.app/Contents/Resources/electron.asar/renderer/api/remote.js:271:17)
    at Object.exception (/private/var/folders/tk/bp9b866n115c6s97xv5x518c0000gn/T/AppTranslocation/2495B446-26EC-4DE6-997A-820A11C22FD9/d/Notable.app/Contents/Resources/electron.asar/renderer/api/remote.js:219:30)
    at metaToValue (/private/var/folders/tk/bp9b866n115c6s97xv5x518c0000gn/T/AppTranslocation/2495B446-26EC-4DE6-997A-820A11C22FD9/d/Notable.app/Contents/Resources/electron.asar/renderer/api/remote.js:223:28)
    at Object.descriptor.get [as webContents] (/private/var/folders/tk/bp9b866n115c6s97xv5x518c0000gn/T/AppTranslocation/2495B446-26EC-4DE6-997A-820A11C22FD9/d/Notable.app/Contents/Resources/electron.asar/renderer/api/remote.js:142:16)
    at webContents (/private/var/folders/tk/bp9b866n115c6s97xv5x518c0000gn/T/AppTranslocation/2495B446-26EC-4DE6-997A-820A11C22FD9/d/Notable.app/Contents/Resources/app.asar/node_modules/electron-context-menu/index.js:6:32)
    at create (/private/var/folders/tk/bp9b866n115c6s97xv5x518c0000gn/T/AppTranslocation/2495B446-26EC-4DE6-997A-820A11C22FD9/d/Notable.app/Contents/Resources/app.asar/node_modules/electron-context-menu/index.js:9:2)
    at module.exports (/private/var/folders/tk/bp9b866n115c6s97xv5x518c0000gn/T/AppTranslocation/2495B446-26EC-4DE6-997A-820A11C22FD9/d/Notable.app/Contents/Resources/app.asar/node_modules/electron-context-menu/index.js:192:3)
    at ContextMenu.external_electron_context_menu_ [as _makeMenu] (file:///private/var/folders/tk/bp9b866n115c6s97xv5x518c0000gn/T/AppTranslocation/2495B446-26EC-4DE6-997A-820A11C22FD9/d/Notable.app/Contents/Resources/app.asar/webpack:/src/renderer/components/main/extra/context_menu.tsx:45:5)
    at ContextMenu._makeMenu [as initAttachmentMenu] (file:///private/var/folders/tk/bp9b866n115c6s97xv5x518c0000gn/T/AppTranslocation/2495B446-26EC-4DE6-997A-820A11C22FD9/d/Notable.app/Contents/Resources/app.asar/webpack:/src/renderer/components/main/extra/context_menu.tsx:68:10)
    at ContextMenu.initAttachmentMenu [as componentDidMount] (file:///private/var/folders/tk/bp9b866n115c6s97xv5x518c0000gn/T/AppTranslocation/2495B446-26EC-4DE6-997A-820A11C22FD9/d/Notable.app/Contents/Resources/app.asar/webpack:/src/renderer/components/main/extra/context_menu.tsx:24:10)
```

**Comment by ryan-mccaffrey** [comment] 2018-12-27 07:11
Solution: Move the Notable application out of the Downloads folder in Finder (I moved into /Applications) and then open the application again. Unsure why this error is dependent on the application's location

**Comment by fabiospampinato** [comment] 2018-12-27 07:56
Thanks for reporting the issue. I'm not sure about this, but I think that there may be some issues when apps aren't executed from `/Applications`. Many apps prompt the user asking to be moved to the `/Applications` directory, maybe I'll do the same thing in the same update, I have to document myself about this 🤔

**Comment by fabiospampinato** [comment] 2019-01-19 15:43
@ryan-mccaffrey I don't think this is related to the location of the executable, I'm closing this as duplicate of #283 as others there have expressed similar problems.

**Closed by fabiospampinato** 2019-01-19 15:43 UTC
Labels: bug
