### ISSUE TITLE
New notes sometimes keep the filename "Untitled (n).md" on disk

### ISSUE THREAD

**Issue by dps** [fabiospampinato/notable#175] opened 2019-01-03 06:06 UTC
I haven't quite figured out exactly what causes this to happen, but I see it somewhat frequently.

At least the following steps seem pretty reliable:
 - create a new note by typing in a search query with no results e.g. ":christmas_tree:" or "1600 Ampitheatre Parkway"
 - press the new note button
 - edit the note content for a little while
 - save the note with Command-S

Observe that the file is called "Untitled (n).md" on disk.

**Comment by fabiospampinato** [comment] 2019-01-03 12:49
@dps I'm not sure I'm following, the problem is that sometimes a note's title doesn't change? or that the title changes but the file is not renamed? or that the title changes, the file is renamed, but the old one is not deleted?

**Comment by fabiospampinato** [comment] 2019-01-24 01:08
As a rule of thumb the first line of the note is used for inferring the title, if that line just contains an emoji we won't have much to work with, as the emoji will probably be removed for sanitization purposes.

Closing as no more info have been provided.

**Closed by fabiospampinato** 2019-01-24 01:08 UTC
Labels: needs more info
