### ISSUE TITLE
Autosuggest Tags

### ISSUE THREAD

**Issue by brycekunkel** [fabiospampinato/notable#424] opened 2019-02-06 19:07 UTC
### Feature description

Would love to see the "Add Tags" input use an auto-suggest functionality based on the existing tags, again using a fuzzy search option. 

### Feature motivation

This would help with accidentally mistagging notes, as well as make the UX more enjoyable and a little easier.

**Comment by fabiospampinato** [comment] 2019-02-06 19:20
Duplicate of #20.

**Closed by fabiospampinato** 2019-02-06 19:20 UTC

**Comment by brycekunkel** [comment] 2019-02-06 19:22
Sorry! Thanks for closing it out!
