### ISSUE TITLE
Notable menu not shown on Linux

### ISSUE THREAD

**Issue by pacharanero** [fabiospampinato/notable#138] opened 2018-12-30 17:25 UTC
Installed via `.deb` package
Platform: Linux Mint 19.2 (Ubuntu based)

I'm presuming that where instructions say things like "You can open your data directory via `Notable -> Open Data Directory`." there should be some kind of menu at the top of the screen, unfortunately there doesn't seem to be a menu shown in Linux, unless I'm doing something wrong.

![image](https://user-images.githubusercontent.com/2348385/50549606-a4517280-0c57-11e9-92c5-f14dc825f0b4.png)

Great project though, I've been looking for something simple yet powerful like this for some time.

**Comment by fabiospampinato** [comment] 2018-12-30 17:33
Duplicate of #3, will be fixed in the next release.

**Closed by fabiospampinato** 2018-12-30 17:33 UTC

**Comment by pacharanero** [comment] 2018-12-30 18:58
Thanks and apologies for opening duplicate issue. Using `Alt` does fix the problem for me as well, although having the menu shown by default would be preferable.
