### ISSUE TITLE
Highlight toolbar paperclip icon if a note has attachments

### ISSUE THREAD

**Issue by amelandri** [fabiospampinato/notable#298] opened 2019-01-18 10:37 UTC
### Feature description

When a note has attachments, the paper clip icon should be highlighted. 

### Feature motivation

It would be easier to see if a note has attachments, especially when in focus mode and the middle bar is hidden (in the middle bar a user can see if a note has attachments).

**Comment by fabiospampinato** [comment] 2019-01-18 12:59
Duplicate of #224

**Closed by fabiospampinato** 2019-01-18 12:59 UTC
