### ISSUE TITLE
add a cards view 

### ISSUE THREAD

**Issue by absir1949** [fabiospampinato/notable#317] opened 2019-01-22 05:20 UTC
### Feature description
we can will note by cards view,then we can see more information.like the 
![image](https://user-images.githubusercontent.com/14873265/51513930-64da0880-1e48-11e9-9796-9ad5d98d3ead.png)

**Comment by fabiospampinato** [comment] 2019-01-22 13:23
I think this is mostly a duplicate of #244 and #216

**Closed by fabiospampinato** 2019-01-22 13:23 UTC
