### ISSUE TITLE
Note Creation inside a Notebook

### ISSUE THREAD

**Issue by mediter** [fabiospampinato/notable#136] opened 2018-12-30 16:33 UTC
Currently, when creating a new note while the app is showing the content of a selected notebook, the new note would be just a plain markdown with no tag.

If the user want to move the note into a particular notebook, one would have to add 'Notebooks/notebook_name' tag to the note manually.

Personally, I think there are two ways to improve this journey:

1. when creating a new note while inside a notebook, add the associated tag of that notebook to the new note automatically. This would, of course, depend on the expected default behavior of the majority of Notable users.

2. when adding tags to note, list existing tags as options or offer existing tags as autocomplete

**Comment by fabiospampinato** [comment] 2018-12-30 16:48
Duplicate of #96 (fixed).

**Closed** 2018-12-30 16:49 UTC

**Comment by mediter** [comment] 2018-12-30 17:00
![new_note_untagged](https://user-images.githubusercontent.com/57368/50549396-2ad97480-0c97-11e9-9d99-8c17260973e4.gif)

![screen shot 2018-12-31 at 12 54 19 am 2](https://user-images.githubusercontent.com/57368/50549407-50ff1480-0c97-11e9-8129-b6e80c653f53.jpg)

judging by the timestamp, v. 1.0.1 does not contain the fix for 
https://github.com/fabiospampinato/notable/issues/96

**Comment by fabiospampinato** [comment] 2018-12-30 17:03
yes I have to publish v1.1.0 yet, hopefully I can do this today or tomorrow.
