### ISSUE TITLE
View Bug for Certain URLs

### ISSUE THREAD

**Issue by VictorXLR** [fabiospampinato/notable#246] opened 2019-01-09 00:15 UTC
### Current behavior
Provides this as output 
```
{\left\lbrace{h}\right\rbrace}{\left\lbrace{\mathtt{{{\left\lbrace{p}\right\rbrace}}}}\right\rbrace}{\left\lbrace{s}\right\rbrace}{\frac{{}}{{/}}}{\left\lbrace{w}\right\rbrace}{\left\lbrace{w}\right\rbrace}{\left\lbrace{w}\right\rbrace}.{\left\lbrace{c}\right\rbrace}{\left\lbrace{s}\right\rbrace}.{\left\lbrace{u}\right\rbrace}{\left\lbrace{b}\right\rbrace}{\left\lbrace{c}\right\rbrace}.{\left\lbrace{c}\right\rbrace}{\frac{{{\left\lbrace{a}\right\rbrace}}}{{\lbrace}}}~murphyk/MLbook/index.html
``` 
when trying to paste this `https://www.cs.ubc.ca/~murphyk/MLbook/index.html ` url. 

Create a new note
place this url: https://www.cs.ubc.ca/~murphyk/MLbook/index.html 

Save & exit editing mode
### Expected behavior

Should render the same link

Should render same data, provides intelligible information,
URL doesnt stay the same
### Environment

- **OS**: [e.g. Windows 10, Ubuntu 16.04]
Solus Budgie 3.999
- **Notable version**: [e.g. v1.1.0]
Version 1.1.0. Latest Release

**Comment by bendem** [comment] 2019-01-09 10:55
Duplicate of https://github.com/fabiospampinato/notable/issues/235

**Closed** 2019-01-09 11:01 UTC
