### ISSUE TITLE
Prompt unsaved ( Edit Mode ) on close

### ISSUE THREAD

**Issue by drupalshift** [fabiospampinato/notable#217] opened 2019-01-06 07:41 UTC
Since it's casual to hit `Ctrl + W `instead of `Ctrl + S` accidentally 
Check if the editor is in edit mode on close and prompt to save

**Comment by fabiospampinato** [comment] 2019-01-06 16:00
I think we should just autosave in that scenario, so I'm closing this as duplicate of #159 .

**Closed by fabiospampinato** 2019-01-06 16:00 UTC
