### ISSUE TITLE
An Error Occurred!

### ISSUE THREAD

**Issue by SadWood** [fabiospampinato/notable#2] opened 2018-12-27 01:44 UTC
Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Error (file:///private/var/folders/t4/4j2cdwxx5w16njjpv19lsw680000gn/T/AppTranslocation/5AC7B32C-02D3-4548-AD03-4759A2C68667/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:13:314)
    at ca (file:///private/var/folders/t4/4j2cdwxx5w16njjpv19lsw680000gn/T/AppTranslocation/5AC7B32C-02D3-4548-AD03-4759A2C68667/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:14:166)
    at t (file:///private/var/folders/t4/4j2cdwxx5w16njjpv19lsw680000gn/T/AppTranslocation/5AC7B32C-02D3-4548-AD03-4759A2C68667/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:118:40)
    at af (file:///private/var/folders/t4/4j2cdwxx5w16njjpv19lsw680000gn/T/AppTranslocation/5AC7B32C-02D3-4548-AD03-4759A2C68667/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:150:11)
    at fg (file:///private/var/folders/t4/4j2cdwxx5w16njjpv19lsw680000gn/T/AppTranslocation/5AC7B32C-02D3-4548-AD03-4759A2C68667/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:154:21)
    at Q (file:///private/var/folders/t4/4j2cdwxx5w16njjpv19lsw680000gn/T/AppTranslocation/5AC7B32C-02D3-4548-AD03-4759A2C68667/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:168:468)
    at Ag (file:///private/var/folders/t4/4j2cdwxx5w16njjpv19lsw680000gn/T/AppTranslocation/5AC7B32C-02D3-4548-AD03-4759A2C68667/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:204:16)
    at lh (file:///private/var/folders/t4/4j2cdwxx5w16njjpv19lsw680000gn/T/AppTranslocation/5AC7B32C-02D3-4548-AD03-4759A2C68667/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:205:271)
    at mh (file:///private/var/folders/t4/4j2cdwxx5w16njjpv19lsw680000gn/T/AppTranslocation/5AC7B32C-02D3-4548-AD03-4759A2C68667/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:220:233)
    at Ph (file:///private/var/folders/t4/4j2cdwxx5w16njjpv19lsw680000gn/T/AppTranslocation/5AC7B32C-02D3-4548-AD03-4759A2C68667/d/Notable.app/Contents/Resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:219:143)

**Comment by fabiospampinato** [comment] 2018-12-27 01:50
Thanks for the report! Unfortunately the error is a big generic, can you describe the actions that lead to this error? Can you reproduce it in any way?

**Comment by SadWood** [comment] 2018-12-27 01:58
> Thanks for the report! Unfortunately the error is a big generic, can you describe the actions that lead to this error? Can you reproduce it in any way?

when I editing note, use the search notes function at the same time, error throw.
sorry, my English is not good, I don't know if I have expressed myself clearly.

**Comment by fabiospampinato** [comment] 2018-12-27 02:04
Thanks for the help, I'll try to get it fixed as soon as possible.

**Comment by TheConnMan** [comment] 2018-12-27 02:08
I just ran into this as well. Typed up a test note, went straight to the search box, typed a term, and hit enter, then got the error. v1.0.1 on Ubuntu, installed from the .deb. Thanks,

**Comment by pajtai** [comment] 2018-12-27 05:07
Same here. I haven't created any notes yet. I entered a search term (the search results showed), but then when I hit enter or click the search icon the error shows up.

**Comment by James-Quigley** [comment] 2018-12-27 22:57
Looks like #21 is a duplicate of this. I just submitted pr #63 which I believe fixes the issue

**Closed** 2018-12-28 21:20 UTC
Labels: bug
