### ISSUE TITLE
Feature request: List all existing tags when adding new tags from the toolbar

### ISSUE THREAD

**Issue by fengzilong** [fabiospampinato/notable#121] opened 2018-12-29 03:48 UTC
re-typing the same word is really tedious

**Comment by fabiospampinato** [comment] 2018-12-29 03:50
Duplicate of #20

**Closed** 2018-12-29 03:50 UTC

**Comment by fengzilong** [comment] 2018-12-29 03:56
I saw that issue, but I think it's a little different.

It's requesting autocomplete feature for [linking syntax](https://github.com/fabiospampinato/notable/blob/master/resources/tutorial/notes/10%20-%20Linking%20Attachments%E2%88%95Notes%E2%88%95Tags.md)



![xnip2018-12-363_11-55-08](https://user-images.githubusercontent.com/9125255/50533235-a258b800-0b60-11e9-80f3-a93b5f599137.jpg)

but I mean the toolbar 😅 can we reopen this?

**Comment by fabiospampinato** [comment] 2018-12-29 04:01
I've changed the title of the issue I linked to and added a commend about your use case, both uses are basically about implementing some autocompletion features, of course once they are available they will be used everywhere it makes sense to use them, including (most importantly IMHO) when editing tags.
