### ISSUE TITLE
when searching - no result from the contain of the note only title and then this exception

### ISSUE THREAD

**Issue by fabienbelmonte** [fabiospampinato/notable#130] opened 2018-12-29 23:47 UTC
Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Error (file:///C:/PortApp/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:13:314)
    at ca (file:///C:/PortApp/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:14:166)
    at t (file:///C:/PortApp/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:118:40)
    at af (file:///C:/PortApp/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:150:11)
    at fg (file:///C:/PortApp/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:154:21)
    at Q (file:///C:/PortApp/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:168:468)
    at Ag (file:///C:/PortApp/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:204:16)
    at lh (file:///C:/PortApp/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:205:271)
    at mh (file:///C:/PortApp/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:220:233)
    at Ph (file:///C:/PortApp/Notable/resources/app.asar/webpack:/node_modules/react-dom/cjs/react-dom.production.min.js:219:143)

**Comment by fabiospampinato** [comment] 2018-12-30 13:40
The exception is a duplicate of #2, searching in the content is a duplicate of #48

**Closed by fabiospampinato** 2018-12-30 13:40 UTC
