### ISSUE TITLE
Files already under `attachments` dir should not be copied again

### ISSUE THREAD

**Issue by roccowang** [fabiospampinato/notable#265] opened 2019-01-11 08:16 UTC
### Feature description

I think it's better for notable to have the ability to detect that i chose a file already under `${currentDataDirectory}/attachments`, and avoid copying that file again.

### Feature motivation

Copying attachments already under attachments dir would make the dir messy.

**Comment by Trenar** [comment] 2019-01-11 11:11
partial duplicate of my comment under #32 , but with a better title

**Comment by fabiospampinato** [comment] 2019-01-11 13:19
Definitely, but this might get tricky as we would have to compute the hash of all the current attachments, and possibly keeping some metadata somewhere about this for performance.

**Comment by fabiospampinato** [comment] 2019-01-11 13:40
@Trenar that's right, only a more general solution would require us to fingerprint attachments.

**Comment by mikaelmello** [comment] 2019-01-11 15:57
What about saving the attachment with its hash (or a part of it) in the filename?

**Comment by Trenar** [comment] 2019-01-11 15:59
Then it won't be possible to copy-paste files manually to that directory

**Comment by fabiospampinato** [comment] 2019-01-11 16:00
@mikaelmello I don't like that, otherwise one need to be real careful when renaming an attachment, and just browsing them becomes a bit messier.

**Comment by roccowang** [comment] 2019-01-14 02:45
> this might get tricky as we would have to compute the hash of all the current attachments, and possibly keeping some metadata somewhere about this for performance

@fabiospampinato since there's meta data to calculate and save, is it possible that notable stores **all** meta data in one dir , say `${HOME}/.notable` and provide an option like 'Open Recent Data Directory ...', allowing user to easily switching between different workspaces? for now i put all my notes in one place, because it takes too much time to choose another data dir.

**Comment by fabiospampinato** [comment] 2019-01-14 02:57
@roccowang 

> is it possible that notable stores all meta data in one dir 

Like also note-level metadata? No.

It shouldn't matter much where other kinds of metadata is stored.

> provide an option like 'Open Recent Data Directory ...', allowing user to easily switching between different workspaces?

Absolutely, let's track this here: https://github.com/fabiospampinato/notable/issues/273

**Comment by mikaelmello** [comment] 2019-01-14 11:17
> Like also note-level metadata? No.
> 
> It shouldn't matter much where other kinds of metadata are stored.

How and where is notable's config saved?

**Closed** 2019-01-16 17:36 UTC
Labels: enhancement
