### ISSUE TITLE
Regression: image attachments not working

### ISSUE THREAD

**Issue by MatanRubin** [fabiospampinato/notable#187] opened 2019-01-03 22:41 UTC
Just updated to 1.1.0 and it's great!
However, looks like image attachments do not render properly.
Here's an example of Notable's tutorial:
<img width="323" alt="screenshot at jan 04 00-39-35" src="https://user-images.githubusercontent.com/4488227/50665473-794d8280-0fb9-11e9-8db4-a66c3d7f9e70.png">

**Comment by ryuheechul** [comment] 2019-01-05 09:57
Same with me, too.
Since I was new to notable, I thought I was doing something wrong, lol. Thank god for the issue!

**Comment by fabiospampinato** [comment] 2019-01-17 16:10
I can't reproduce this on master:

<img width="218" alt="screen shot 2019-01-17 at 17 09 47" src="https://user-images.githubusercontent.com/1812093/51331786-c67e2980-1a7a-11e9-8efc-5a925fb57263.png">

**Comment by gramster** [comment] 2019-01-22 23:40
Reproduces for me on a new install - the one thing I did was move the content location to my iCloud directory under ./notable. I see the icon file there so it seems the @attachment is failing to resolve to the right location.

**Comment by Fastidious** [comment] 2019-01-22 23:57
I can’t reproduce on new install. Running under macOS.

**Comment by gramster** [comment] 2019-01-23 00:54
I cloned the repo and ran from source, and I get a repro. 

The URL that it is trying to open (according to the error in the JS console) is:

    file:///Users/grwheele/Library/Mobile%20Documents/com~%7Ba%7D%7Bp%7D%7Bp%7D/le~CloudDocs/notable/attachments/icon.png

The actual path is:

    /Users/grwheele/Library/Mobile Documents/com~apple~CloudDocs/notable/attachments/icon.png

So there is something funky going on.

**Comment by fabiospampinato** [comment] 2019-01-23 00:59
@gramster Thanks for looking into this. Can you check what's outputted if you put `alert ( attachmentsPath )` [here](https://github.com/fabiospampinato/notable/blob/ed04e45054b544a44afec0d70555cc6d72ac596c/src/renderer/utils/markdown.ts#L103)? Maybe try `alert ( Config.cwd )` also.

**Comment by gramster** [comment] 2019-01-23 01:38
attachmentsPath is /Users/grwheele/Library/Mobile Documents/com~apple~CloudDocs/notable/attachments

Config.cwd is  /Users/grwheele/Library/Mobile Documents/com~apple~CloudDocs/notable

**Comment by fabiospampinato** [comment] 2019-01-23 01:42
@gramster thanks! The paths seem to be computed properly, this might be an issue of properly escaping some characters when generating the url, maybe simply replacing `file://${filePath}` with `file://${encodeURI ( filePath )}` could be enough 🤔

**Comment by gramster** [comment] 2019-01-23 01:44
The return from that function looks fine. But if I inspect the element I see:

    <img src="file:///Users/grwheele/Library/Mobile Documents/com~{a}{p}{p}\le~CloudDocs/notable/attachments/icon.png" class="attachment" data-filename="icon.png" width="192">

**Comment by fabiospampinato** [comment] 2019-01-23 01:46
@gramster no idea why those characters are wrapped in `{}`, maybe some subsequent showdown plugin is messing with this 🤔

**Comment by gramster** [comment] 2019-01-23 01:48
Yes, your suggestion unsurprisingly doesn't change things; it's something happening downstream.

**Comment by gramster** [comment] 2019-01-23 01:52
Seems like a kludge but replacing line 111 with:

            return `<img${$1}src="file://${filePath.replace('~', '%7E')}" class="attachment" data-filename="${$2}"${$3}>`;

fixed it.

**Comment by fabiospampinato** [comment] 2019-01-23 02:07
It looks like using `escape` rather than `escapeURI` might fix the problem then. But that's kind of a deprecated function it seems. Anyway I'll document myself more about this tomorrow and I'll make sure to have this fixed in the next release.

**Comment by fabiospampinato** [comment] 2019-01-23 13:41
It looks like KaTeX was messing with this, thanks anyone for the help.

**Closed** 2019-01-23 13:40 UTC
Labels: bug

**Comment by ryuheechul** [comment] 2019-01-29 00:11
After updating to 1.2.0, I can see images attached in my notes! 👏 🙏
